project:
  type: website

website:
  title: "Analiza Danych w R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - swirl.qmd
      - about.qmd
      - dodatki.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



